### ISSUE TITLE
Rule problem

### ISSUE THREAD

**Issue by greeaaby** [HofeBY/Tasmota-Firmware#1]
THX for your compilation - saves me time... ;-)
Is it correct, that i can't use "rule" anymore? 
I tried:  rule1 1  returned:  {"Command":"Unknown"}

**Comment by HofeBY** [comment]
You can use SCRIPT or RULE, but not the same time on a single ESP.
I chose SCRIPT because of the need in combination with SML.
It is possible to change  user_config_override.h for your own version to compile without SCRIPT but with RULE & MATTER if wished.
Manual is in Liesmich-zuerst.txt how to do.
MATTER is only on ESP32(x) devices possible, not for ESP82(xx) one´s.
Maybe I build the next Version in those two diverent types.

**Comment by HofeBY** [comment]
New .bin Firmware Images with RULE & MATTER with TM14.0.0.4 updated.
New Files to build own version also.
https://github.com/HofeBY/Tasmota-Firmware
